In [8]:
import matplotlib.pyplot as plt

from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
import cPickle

X_pos = cPickle.load(open('raw_data/pos_vects.pkl','rb'))
X_neg = cPickle.load(open('raw_data/neg_vects.pkl','rb'))
X_neu = cPickle.load(open('raw_data/neu_vects.pkl','rb'))

print len(X_pos)
print len(X_neg)
print len(X_neu)

X_pos_train = X_pos[0:275]
X_neg_train = X_neg[0:500]
X_neu_train = X_neu[0:250]
y_pos_train = [1]*len(X_pos_train) + [0]*len(X_neg_train) + [0]*len(X_neu_train)
y_neg_train = [0]*len(X_pos_train) + [1]*len(X_neg_train) + [0]*len(X_neu_train)
y_neu_train = [0]*len(X_pos_train) + [0]*len(X_neg_train ) + [1]*len(X_neu_train)
X_train = X_pos_train + X_neg_train + X_neu_train


X_pos_test = X_pos[275:325]
X_neg_test = X_neg[500:664]
X_neu_test = X_neu[250:299]
y_pos_test = [1]*len(X_pos_test) + [0]*len(X_neg_test) + [0]*len(X_neu_test)
y_neg_test = [0]*len(X_pos_test) + [1]*len(X_neg_test) + [0]*len(X_neu_test)
y_neu_test = [0]*len(X_pos_test) + [0]*len(X_neg_test ) + [1]*len(X_neu_test)
X_test = X_pos_test + X_neg_test + X_neu_test

print len(X_train)
print len(X_test)

325
664
299
1025
263


In [9]:
import numpy as np
y_pos_train = np.array(y_pos_train)
y_neg_train = np.array(y_neg_train)
y_neu_train = np.array(y_neu_train)
y_pos_test = np.array(y_pos_test)
y_neg_test = np.array(y_neg_test)
y_neu_test = np.array(y_neu_test)
n_feature = len(X_train[0])

In [39]:
pca = PCA(n_components=3)
X_train_pca = pca.fit(X_train).transform(X_train)
print len(X_train_pca)
X_test_pca = pca.fit(X_test).transform(X_test)
print len(X_test_pca)

1025
263


In [ ]:
'''
lda = LinearDiscriminantAnalysis(n_components=2)
X_r2 = lda.fit(X, y_pos).transform(X)
'''

In [2]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import SGD

Using Theano backend.


In [47]:
model_pos = Sequential()
model_pos.add(Dense(output_dim=100, input_dim=n_feature, init='uniform', activation='relu'))
model_pos.add(Dropout(0.5))
model_pos.add(Dense(output_dim=50, activation='relu'))
model_pos.add(Dropout(0.5))
model_pos.add(Dense(1, activation='sigmoid'))
model_pos.compile(loss='mse', optimizer='rmsprop')
model_pos.fit(X_train, y_pos_train, nb_epoch=250, batch_size=250, verbose=0)
model_pos.evaluate(X_train, y_pos_train, batch_size=5, verbose = 1)
pos_train = model_pos.predict_proba(X_train, verbose = 0)
model_pos.evaluate(X_test, y_pos_test, batch_size=5, verbose = 1)
pos_test = model_pos.predict_proba(X_test, verbose = 0)

263/263 [==============================] - 0s     


In [20]:
print pos_train
print '**********************************************************************'
print pos_test

[[ 0.8387025 ]
 [ 0.82719409]
 [ 0.68809575]
 ..., 
 [ 0.1138899 ]
 [ 0.06521339]
 [ 0.11552901]]
**********************************************************************
[[ 0.01731077]
 [ 0.71397173]
 [ 0.06388012]
 [ 0.58809507]
 [ 0.65171742]
 [ 0.61928934]
 [ 0.4574776 ]
 [ 0.87812102]
 [ 0.87663293]
 [ 0.60596484]
 [ 0.49899757]
 [ 0.66309607]
 [ 0.11571141]
 [ 0.63874173]
 [ 0.44730565]
 [ 0.34836537]
 [ 0.73357934]
 [ 0.40785661]
 [ 0.74879682]
 [ 0.74397755]
 [ 0.49018812]
 [ 0.55945742]
 [ 0.33272809]
 [ 0.72757721]
 [ 0.64883882]
 [ 0.65316439]
 [ 0.02462844]
 [ 0.67101264]
 [ 0.29317096]
 [ 0.67874354]
 [ 0.75824744]
 [ 0.629924  ]
 [ 0.75968367]
 [ 0.58235431]
 [ 0.04142812]
 [ 0.41874239]
 [ 0.26959306]
 [ 0.55383468]
 [ 0.56997228]
 [ 0.72369134]
 [ 0.63377583]
 [ 0.67024857]
 [ 0.47990748]
 [ 0.24479687]
 [ 0.70837915]
 [ 0.74191433]
 [ 0.52707028]
 [ 0.63024175]
 [ 0.77766162]
 [ 0.47067121]
 [ 0.34493577]
 [ 0.03955523]
 [ 0.72188926]
 [ 0.05433171]
 [ 0.20697677]
 [ 0.1

In [48]:
model_neg = Sequential()
model_neg.add(Dense(output_dim=100, input_dim=n_feature, init='uniform', activation='relu'))
model_neg.add(Dropout(0.5))
model_neg.add(Dense(output_dim=50, activation='relu'))
model_neg.add(Dropout(0.5))
model_neg.add(Dense(1, activation='sigmoid'))
model_neg.compile(loss='mse', optimizer='rmsprop')
model_neg.fit(X_train, y_neg_train, nb_epoch=250, batch_size=250, verbose=0)
model_neg.evaluate(X_train, y_neg_train, batch_size=5, verbose = 1)
neg_train = model_neg.predict_proba(X_train, verbose = 0)
model_neg.evaluate(X_test, y_neg_test, batch_size=5, verbose = 1)
neg_test = model_neg.predict_proba(X_test, verbose = 0)

263/263 [==============================] - 0s     


In [22]:
print neg_train
print '**********************************************************************'
print neg_test

[[ 0.02200309]
 [ 0.01265772]
 [ 0.19512597]
 ..., 
 [ 0.03676439]
 [ 0.11684959]
 [ 0.0184787 ]]
**********************************************************************
[[ 0.41573822]
 [ 0.06166291]
 [ 0.20027874]
 [ 0.08822433]
 [ 0.08923216]
 [ 0.19996367]
 [ 0.22250284]
 [ 0.00466702]
 [ 0.00565284]
 [ 0.09923626]
 [ 0.03418764]
 [ 0.05428409]
 [ 0.21834774]
 [ 0.2244741 ]
 [ 0.10676592]
 [ 0.26354095]
 [ 0.03042609]
 [ 0.06416529]
 [ 0.02412218]
 [ 0.05506787]
 [ 0.14639151]
 [ 0.10697506]
 [ 0.04549751]
 [ 0.04821479]
 [ 0.09665465]
 [ 0.05985378]
 [ 0.08664977]
 [ 0.08720084]
 [ 0.34183067]
 [ 0.09816545]
 [ 0.08946522]
 [ 0.09338446]
 [ 0.011179  ]
 [ 0.0963589 ]
 [ 0.5391466 ]
 [ 0.06381414]
 [ 0.14925036]
 [ 0.12957256]
 [ 0.07819237]
 [ 0.08207116]
 [ 0.08588802]
 [ 0.05636921]
 [ 0.06124606]
 [ 0.01552142]
 [ 0.01219814]
 [ 0.05376567]
 [ 0.06552268]
 [ 0.08728227]
 [ 0.0180496 ]
 [ 0.02222512]
 [ 0.36360168]
 [ 0.93814409]
 [ 0.07839029]
 [ 0.8102324 ]
 [ 0.56372887]
 [ 0.6

In [49]:
model_neu = Sequential()
model_neu.add(Dense(output_dim=100, input_dim=n_feature, init='uniform', activation='relu'))
model_neu.add(Dropout(0.5))
model_neu.add(Dense(output_dim=50, activation='relu'))
model_neu.add(Dropout(0.5))
model_neu.add(Dense(1, activation='sigmoid'))
model_neu.compile(loss='mse', optimizer='rmsprop')
model_neu.fit(X_train, y_neu_train, nb_epoch=250, batch_size=250, verbose=0)
model_neu.evaluate(X_train, y_neu_train, batch_size=5, verbose = 1)
neu_train = model_neu.predict_proba(X_train, verbose = 0)
model_neu.evaluate(X_test, y_neu_test, batch_size=5, verbose = 1)
neu_test = model_neu.predict_proba(X_test, verbose = 0)

263/263 [==============================] - 0s     


In [24]:
print neu_train
print '**********************************************************************'
print neu_test

[[ 0.05783287]
 [ 0.07087944]
 [ 0.09289917]
 ..., 
 [ 0.67766839]
 [ 0.57315534]
 [ 0.70726103]]
**********************************************************************
[[ 0.18480027]
 [ 0.2332235 ]
 [ 0.09493985]
 [ 0.22410308]
 [ 0.0665665 ]
 [ 0.04096757]
 [ 0.09408459]
 [ 0.02726501]
 [ 0.03312709]
 [ 0.20915852]
 [ 0.36237741]
 [ 0.23540089]
 [ 0.29238883]
 [ 0.03796948]
 [ 0.31698975]
 [ 0.14962809]
 [ 0.1415498 ]
 [ 0.43571481]
 [ 0.21851406]
 [ 0.4420625 ]
 [ 0.19345388]
 [ 0.15438393]
 [ 0.2671878 ]
 [ 0.18100493]
 [ 0.35993734]
 [ 0.23232037]
 [ 0.72537637]
 [ 0.15817273]
 [ 0.04101643]
 [ 0.3793065 ]
 [ 0.06363063]
 [ 0.41206786]
 [ 0.16781376]
 [ 0.2339287 ]
 [ 0.07932564]
 [ 0.27802888]
 [ 0.44745561]
 [ 0.21781676]
 [ 0.44539964]
 [ 0.10815485]
 [ 0.31888491]
 [ 0.37930632]
 [ 0.49154183]
 [ 0.49929273]
 [ 0.48666462]
 [ 0.17302714]
 [ 0.47904429]
 [ 0.35870731]
 [ 0.1134608 ]
 [ 0.20392764]
 [ 0.05650448]
 [ 0.06394224]
 [ 0.04371212]
 [ 0.07968295]
 [ 0.16378736]
 [ 0.1

In [ ]:
import operator
def compute_error_rate(y_answer, sentiment_list):
    y_test = []
    for sentiment in sentiment_list:
        index, value = max(enumerate(sentiment), key=operator.itemgetter(1))
        y_test.append(index)
    wrong = 0
    err_index_lst = []
    for i in xrange(len(y_answer)):
        #print y_train[i],y_test[i]
        if y_answer[i] != y_test[i]:
            wrong += 1
            err_index_lst.append(i)
    print float(wrong)/len(y_answer)
    return err_index_lst

In [50]:
y_answer_train = [0]*len(X_pos_train) + [1]*len(X_neg_train)+ [2]*len(X_neu_train)
y_answer_test = [0]*len(X_pos_test) + [1]*len(X_neg_test)+ [2]*len(X_neu_test)

In [51]:
train_sentiment_list = []
for i in xrange(len(X_train)):
    train_sentiment_list.append((pos_train[i][0],neg_train[i][0],neu_train[i][0]))
test_sentiment_list = []
for i in xrange(len(X_test)):
    test_sentiment_list.append((pos_test[i][0],neg_test[i][0],neu_test[i][0]))

err_index_train = compute_error_rate(y_answer_train, train_sentiment_list)
err_index_test = compute_error_rate(y_answer_test, test_sentiment_list)
print err_index_train
print len(err_index_train)
print '**********************************************************'
print len(err_index_test)
print err_index_test

0.0
0.433460076046
[]
0
**********************************************************
114
[0, 2, 12, 15, 22, 26, 28, 34, 35, 36, 43, 50, 52, 54, 60, 62, 65, 66, 69, 71, 72, 76, 77, 78, 80, 81, 82, 83, 84, 88, 96, 98, 100, 101, 106, 108, 110, 116, 119, 120, 127, 132, 134, 135, 136, 141, 142, 143, 147, 150, 153, 154, 157, 159, 162, 167, 170, 171, 173, 174, 175, 176, 177, 185, 186, 188, 190, 194, 195, 197, 204, 206, 211, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 226, 227, 228, 229, 230, 231, 235, 237, 238, 240, 241, 242, 243, 244, 245, 246, 247, 248, 250, 251, 252, 253, 254, 257, 258, 259, 260, 261, 262]


In [3]:
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

print len(X_train_pca)
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
correct_pts = [i for j, i in enumerate(X_train_pca) if j not in err_index_train]
print len(correct_pts)
wrong_pts = [i for j, i in enumerate(X_train_pca) if j in err_index_train]
print len(wrong_pts)


NameError: name 'X_train_pca' is not defined

In [2]:
ax.scatter(zip(*correct_pts)[0], zip(*correct_pts)[1], zip(*correct_pts)[2], c='r')
#ax.scatter(zip(*wrong_pts)[0], zip(*wrong_pts)[1], zip(*wrong_pts)[2], c='g')

ax.set_xlabel('X Label')
ax.set_ylabel('Y Label')
ax.set_zlabel('Z Label')
plt.show()

NameError: name 'ax' is not defined

In [1]:
print len(X_test_pca)
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
correct_pts = [i for j, i in enumerate(X_test_pca) if j not in err_index_test]
print len(correct_pts)
wrong_pts = [i for j, i in enumerate(X_test_pca) if j in err_index_test]
print len(wrong_pts)

NameError: name 'X_test_pca' is not defined

In [46]:
ax.scatter(zip(*correct_pts)[0], zip(*correct_pts)[1], zip(*correct_pts)[2], c='r')
ax.scatter(zip(*wrong_pts)[0], zip(*wrong_pts)[1], zip(*wrong_pts)[2], c='g')

ax.set_xlabel('X Label')
ax.set_ylabel('Y Label')
ax.set_zlabel('Z Label')
plt.show()

In [33]:
target_names = ['Positive','Negative','Neutral']
print target_names

# Percentage of variance explained for each components
print('explained variance ratio (first three components): %s'
      % str(pca.explained_variance_ratio_))

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

pos_begin = 0
pos_end = len(X_pos)
neg_begin = len(X_pos)
neg_end = len(X_pos) + len(X_neg)
neu_begin = len(X_pos) + len(X_neg)
neu_end = len(X_pos) + len(X_neg) + len(X_neu)
#plt.scatter(zip(*X_r)[0], zip(*X_r)[1], c='r', label=target_name)
ax.scatter(zip(*X_r[pos_begin:pos_end])[0], zip(*X_r[pos_begin:pos_end])[1], zip(*X_r[pos_begin:pos_end])[2], c='r', label=target_name)
ax.scatter(zip(*X_r[neg_begin:neg_end])[0], zip(*X_r[neg_begin:neg_end])[1], zip(*X_r[neg_begin:neg_end])[1], c='g', label=target_name)
ax.scatter(zip(*X_r[neu_begin:neu_end])[0], zip(*X_r[neu_begin:neu_end])[1], zip(*X_r[neu_begin:neu_end])[1], c='b', label=target_name)
ax.set_xlabel('X Label')
ax.set_ylabel('Y Label')
ax.set_zlabel('Z Label')
'''
for c, i, target_name in zip("rgb", [0, 1, 2], target_names):
    print i
    plt.scatter(X_r[y == i, 0], X_r[y == i, 1], c=c, label=target_name)
plt.legend()
plt.title('PCA of IRIS dataset')
'''
'''
plt.figure()
for c, i, target_name in zip("rgb", [0, 1, 2], target_names):
    plt.scatter(X_r2[y == i, 0], X_r2[y == i, 1], c=c, label=target_name)
plt.legend()
plt.title('LDA of IRIS dataset')
'''
plt.show()

325
333
304
962
['Positive', 'Negative', 'Neutral']
explained variance ratio (first two components): [ 0.04563301  0.02991236  0.01762879]
